site_name: PUMAS
site_description: A C99 library for the transport of high energy &mu; or &tau;
site_author: Valentin Niess
copyright: LGPL-3.0

repo_url: https://github.com/niess/pumas-docs
edit_uri: edit/master/docs/docs

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - PUMAS API: api/
  - Materials:
    - Materials Description Files: materials-description-files.md
    - Energy loss tables: energy-loss-tables.md

theme:
  name: readthedocs
  navigation_depth: 2
  highlightjs: true
  hljs_languages:
    - C

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex # pip install pymdown-extensions

extra_css: [extra.css]

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
